{% set name = "d3ploy" %}
{% set version = "1.0.1" %}
{% set sha256 = "7fce6ec437b84d15abc74748403696a2fdbd47a37a63c7402be4041c19f36e41" %}

package:
  name: cyclus-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ergs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - cyclus
  run:
    - python

test:
  requires: 
    - nose
  imports:
    - d3ploy
  commands:
    - nosetests

about:
  home: http://github.com/ergs/d3ploy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Demand Driven Deployment for Cyclus'

  description: |
    d3ploy is a demand driven deployment archetype for the cyclus fuel
    cyclus simulator. It uses a variety of methods to predict future
    deployment needs. These include non-optimizing methods, sochastically
    optimizing methods, and deterministic methods. 

extra:
  recipe-maintainers:
    - flanflanagan
    - scopatz
