travis:
  secure:
    BINSTAR_TOKEN: Yx2zEgj0VkvRklkTleEAVJlwWZIIUjzjtKaI9j9aIeWQK+9/D+IiUTKupvHSoFGCM4/PGlBdGZwCgYTLIF/UtTPi74c+Ik7ze2ky9LAalyqx6BINWiwuCCQQF9jpRRqlgEFZvcBlNaSaLcodRtUjuNoXHzE/GceMdKjT07MtZsLvg18PlnmJ1/ucplFY6wXLZ6ARrhGrJ6jDkarodIz7fZ1joq6NYpWfVhIZMNOTnpPJ31LPIkBWOjFtJvUr0kq1E8PyEZ3ynE/xvsUkfVl9X1km/WOAUyz3wPiv8p3z+0F1YHA7798myKBywj1cNJJsaADfxI79f/kbCg1N1wDLCkYzoish2xZOeOk4Ewm57qPck6SXYjTPBAbhR81+cECj/YCqFMpbcqUZMBCXibY/KLGqCWt2A9bsX53CnqAqCkA2YsaOeSTn/EpPWEvKULToO4VpISgxlZozG8/+F1nxETqvQPWmdUjdYvIA3DAgW6hyto4R7271zmm7z1NQrDQijnEhLnqTWccIAJQ5cGXKsqHaau4sXAgQtqPvQSEs63KNCPI4WpCXkgx3NGqQ3VPoPOH9dZSWZjryGisv3Xd65qVStr5kuBpuIkY66HxdL/gJuqIsxECE+IvA/DQwCUsq8M8FqH7Wl3LHQ9mfaqQzBXW0brmlTxNmAOcFQ5vDA1o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
