travis:
  secure:
    BINSTAR_TOKEN: H92+K4mYGCk4vo6D4tgHFalw/QFkMmUZKR6Zxpf9e/fzGMAqoWo6JXPcJ0O5eANpf1/CUIY7tOY27nmu8DqYEwTFCYPqJSt6xl+zBbvCI686PFST1rK17gpcPfqpZCR+VWMbB7/mRYdKsYeSFvS0xfOApGMD+pLrZTxnv8JIohAgQBY772GNdMV8TU7IFTqK6LmC18sTyFfP/P3mX5v58t1/JBaAmdfCeBIVoSWIS2YDqx0CSY81e1TSrVqW57AfTctKSzov3P0swg42V27n1ATRRXHqv+aGhDBNUjKJQudCuorL4EQfH3ntrgQB/kfhgOEStMvcGT6yiHN2yjlMsoAVUgKdOsAELR4xZdz3yVJP4cTwbN4owZot8UnzrOsbd/ADwVV39Bzw7CQ5rXzNkO4mEWgEYEaLVUmoPzlFO1xX/hz2kHSNXbwp35AdYPwWPyF70OVzO0E1BGG4FJ4+dYshmIRu2bthRO7RwxnUG4CW1m+KVM4FlnCJz1xctisi7Lbi9QpsrPzRFjLj3JxA1UT9CEQc53GJbAj23ijP8h4vgNokUO7VQZhUt9LadQJrwUhsGZ+cdFNgkJ+M/QZzdPjRgGQ/yQKFe/ydXcLsOicPxk8OKukfO8jCQhigfNCZUR/1jJCDhuyEyifa6u1Z+4JyC4GPn8Mo7Aw7MDUM/hM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
