travis:
  secure:
    BINSTAR_TOKEN: YoisIqdyKShSgJ/JOtGh4mRvHd56LT4xLqYFT1gxy64ezqXhaBrOlHPGBCirrW+fqtFXPmlY7QC6X8ZNpaTZwgLEbElBpjSMObS7BVMtq6UqJ2Ij/2jm4Xxld7ccVndygQlCIs80A4f3xr+3B43JhOBFS4AyJrx6O6W2tbHdrA+CVX/i6NvOI9azGvr18yQnxcCVjMS/ywzm8GtBzGGykAUnWVxWiUOc7janckB8rMlXvjykMTKbwB3Qa54gfBkV3EB0ZLpEmhRYQvnd7+XPZhjLdoSpSu6AVlIePTWvShKeclRXyJUoc4AfLAuLsmD+LdC4BPrf7xL5eWtA4QiZfpadJN/e0iqqMt/7rNsbDscVg40pv+/5A1D5DskJAwVe4wxe3wmNH3AsQmEBs0shzAeuGwwgUnWS0dtSmVsoNoSnpp1OcdpGrrJ+jJucbKrvTvuYIUNMi18XwupXMgv3IjaawSZzkBI8ghqpW+Vii/u/enCElB01cDKFoSA2ZmCO/ugF6Rlj91WRkqUc/HT7NE/GOlqxn6ZwK0sWEqtS/kFgGiWddKu28OgQiuiTmrY4cNRvawTDGcExr5Twqhy2A6jXNs1efh/fPjVTCMDBBhgCCOm8oOiF3Y9Almf88EablKC+fX/EWchWUfWpGOKSaWf/jvruLf+QiwdXzXBn3TE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
