travis:
  secure:
    BINSTAR_TOKEN: k1JVQ+4YM/MQKgkF3s/C1TRWX0rizJTbvuCzRlz027sMOZGu7yy8D9PZSGHP6yUuBPMBgkddgYmQupccXq41Itq7WKa/fX/hqQzVdXuvKTn3/K0o0xg1OkSSYUqDgWeVmg+Z8A1O6ezZE6zm1WHL8p0OaRJ2luKRRNE/7XAZRa7cpXZLXinfT49XTbmDiRESWAIt9snkm8NxgLQR2W2g2wYUkD34aa11/fpaZIZquHZ3NNWTLkUgxrnVrLzEHx041685IR+7avkG8jn1xGsRBEFZ7fNQUQY9/+9xonXQv59sl7POeb7Bo8EDddrOCZxqTXryXd3IpMRI4AShE57DhFq4kXsvs0iVR6WJsCosDQ7scq4qZhoJMgFSj0lJCjZx8gnuOH9/KcSpCjnziC1pnqFu2cw6NQwEkSTdzPIJm8CUSZxpTMA5/6tMdfqcO6h9/7mVVL5cQE220O14Q/bZ2z99LnIdIcV8z4cJ7YUXTSENEb3V1oflMRR+8Wcifxl4xcz9eO+8eQutjZAM6ZFRsAtxQcb/1yjlkXtDhqBzZ8lfnz+Q+7JvmMxtvSyXiQTj/afYyZh6MVZVLy1dTqkeP2sRndqpmYAZJJEmccv4aR7OTcQSRaZIDw3iP/SOMLkV5SC9Dxg1PWrMSzj/CdpebelEcANa4lkDhs9PCnolE+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
